import { ProjectsSectionType } from '@/lib/types/sections'
import { getId } from '@/lib/utils/helper';


export const projectsSection: ProjectsSectionType = {
    title: 'my projects',
    projects: [
    {
        id: getId(),
        name: '株式会社グラスト',
        description: 'デザイン | フロントエンド',
        url: 'https://www.grust.co.jp/',
        repo: 'https://github.com/vatsalsinghkv/beautiful-animations',
        img: '/projects/grusts.png',
        category: 'Web Application',
        year: 2023,
        tags: ['Laravel', 'jquery'],
    },
    {
        id: getId(),
        name: '熊本の居宅介護支援',
        description: 'デザイン | フロントエンド',
        url: 'https://www.care-plus.jp/',
        repo: 'https://github.com/vatsalsinghkv/easy-fix',
        img: '/projects/care-plus.png',
        category: 'Web Application',
        year: 2023,
        tags: ['React', 'Tailwind'],
    },
    {
        id: getId(),
        name: '株式会社東土地測量',
        description: 'フロントエンド | バックエンド',
        url: 'https://azuma-office.jp/',
        repo: 'https://github.com/vatsalsinghkv/image-animations',
        img: '/projects/office.png',
        category: 'Web Application',
        year: 2023,
        tags: ['Wordpress', 'jquery'],
    },
    {
        id: getId(),
        name: '株式会社にんべん',
        description: ' デザイン | フロントエンド',
        url: 'https://www.ninben.co.jp/',
        repo: 'https://github.com/vatsalsinghkv/todo-app',
        img: '/projects/ninben.png',
        category: 'Web Application',
        year: 2022,
        tags: ['Vue.js', 'Jquery'],
    },
    {
        id: getId(),
        name: '奈良の司法書士',
        description: 'デザイン | フロントエンド ',
        url: 'https://koyama-houmu.com/',
        repo: 'https://github.com/vatsalsinghkv/remotive-jobs',
        img: '/projects/koyama-houmu.png',
        category: 'Web Application',
        year: 2022,
        tags: ['Wordpress'],
    },
    {
        id: getId(),
        name: 'Starboard',
        description: 'バックエンド',
        url: 'https://iboardjapan.com/',
        repo: 'https://github.com/vatsalsinghkv/rest-countries-api',
        img: '/projects/iboard.png',
        category: 'Web Application',
        year: 2022,
        tags: ['Wordpress'],
    },
    {
        id: getId(),
        name: 'mint ',
        description: 'デザイン | フロントエンド',
        url: 'https://mint-vc.com/',
        repo: 'https://github.com/vatsalsinghkv/rock-paper-scissors',
        img: '/projects/mint.png',
        category: 'Web Application',
        year: 2022,
        tags: ['React'],
    },
    {
        id: getId(),
        name: 'KUMON',
        description: 'フロントエンド | バックエンド',
        url: 'https://www.kumon.ne.jp/',
        repo: 'https://github.com/vatsalsinghkv/todo-app',
        img: '/projects/kumon.png',
        category: 'Web Application',
        year: 2022,
        tags: ['jquery'],
    },
    {
        id: getId(),
        name: '神戸牛 通販',
        description: ' デザイン | フロントエンド',
        url: 'https://www.kobebeef.co.jp/',
        repo: 'https://github.com/vatsalsinghkv/todo-app',
        img: '/projects/kobebeef.png',
        category: 'Web Application',
        year: 2022,
        tags: ['React'],
    },
    {
        id: getId(),
        name: '株式会社come-te',
        description: ' デザイン | フロントエンド',
        url: 'https://comete.design/',
        repo: 'https://github.com/vatsalsinghkv/todo-app',
        img: '/projects/comete.png',
        category: 'Web Application',
        year: 2022,
        tags: ['WordPress'],
    },
    {
        id: getId(),
        name: '佐藤歯科医院',
        description: 'フロントエンド',
        url: 'https://www.dentist-sato.com/',
        repo: 'https://github.com/vatsalsinghkv/todo-app',
        img: '/projects/dentist-sato.png',
        category: 'Web Application',
        year: 2022,
        tags: ['WordPress'],
    },
    
    {
        id: getId(),
        name: '佐藤歯科医院',
        description: 'フロントエンド',
        url: 'https://www.kingjim.co.jp/sp/hello/',
        repo: 'https://github.com/vatsalsinghkv/todo-app',
        img: '/projects/kin.png',
        category: 'Web Application',
        year: 2022,
        tags: ['WordPress'],
    },
    // {
    //     id: getId(),
    //     name: 'nexter',
    //     description: '',
    //     url: '',
    //     repo: 'https://github.com/vatsalsinghkv/nexter',
    //     img: '/projects/food-ordering.jpg',
    //     category: 'Mobile Application',
    //     year: 2021,
    //     tags: ['html', 'sass'],
    // }
    ],
};